### ISSUE TITLE
Column Widths

### ISSUE THREAD

**Issue by RyRy1234Ry** [sbi-rviot/ph_table#11]
Hi,
I have just come across this and it is very useful. I was wondering if there is a way to make the columns wider - some of my text is cut off when the table is created.
Many thanks

**Comment by sbi-rviot** [comment]
Hello @RyRy1234Ry !
Thank you for using my library :) - Yes, it is doable.
I'll try come back to you this week.
Renaud

**Comment by sbi-rviot** [comment]
It have been added to the latest version. Could you please confirm and please start this library if you have not yet to help the community! Thanks
