### ISSUE TITLE
non white lines

### ISSUE THREAD

**Issue by michelkluger** [sbi-rviot/ph_table#13]
would be nice to have non white lines for a white background to contrast properly

**Comment by sbi-rviot** [comment]
Hello @michelkluger!
Thank you for this comment - do you have a specific example? (a picture might help!)

**Comment by michelkluger** [comment]
in my use case, I add the pretty_html_table to an email, but the background of the email body is white, so non_white background options would be really

![image](https://user-images.githubusercontent.com/50880307/121660027-2a1dad00-caa3-11eb-85c1-38644a75a7ea.png)

**Comment by sbi-rviot** [comment]
hmm so you could choose the second one?
Then you should also be able to choose the color of the font no?

**Comment by michelkluger** [comment]
I mean more, being able to choose the background color pair, or at least the the white background to be a light grey, for instance

**Comment by michelkluger** [comment]
very cool library BTW

**Comment by sbi-rviot** [comment]
Done @michelkluger 
now you can change the even color and the even background color.
Could you test and let me know?

**Comment by michelkluger** [comment]
works for white, and black, then I tested for "grey" and "grey_light" neither worked

**Comment by sbi-rviot** [comment]
I tried this one and it works for instance:

build_table(df, 'blue_light'
            , even_color='white'
            , even_bg_color='grey')

You could also you HEX naming ("#a9a9a9") and it would also work.

**Comment by michelkluger** [comment]
for me generates something like this,

![image](https://user-images.githubusercontent.com/50880307/121666489-9ac7c800-caa9-11eb-8bb1-74385ffd7c00.png)

build_table(
        df, "blue_light", even_color="white", even_bg_color="grey  ", font_size="15px", index=True
    )

**Comment by sbi-rviot** [comment]
Are you sure you have the appropriate version (0.9.8)?
![Capture](https://user-images.githubusercontent.com/47696569/121668742-e54a4400-caab-11eb-9ee3-e78b92f2159a.PNG)

**Comment by michelkluger** [comment]
yes, I double checked

**Comment by sbi-rviot** [comment]
I am not mistaken, in your code, it is "grey ". The space after grey might be causing the issue.
Could you check?

**Comment by michelkluger** [comment]
build_table(
       df, "blue_light", even_color="white", even_bg_color="grey", font_size="15px", index=True
    )

same result

**Comment by michelkluger** [comment]
> Are you sure you have the appropriate version (0.9.8)?
> ![Capture](https://user-images.githubusercontent.com/47696569/121668742-e54a4400-caab-11eb-9ee3-e78b92f2159a.PNG)

in your print there is also a issue in the formatting of the index, related to issue #12

**Comment by sbi-rviot** [comment]
I am confused now - what is your issue? the add-on you added issue #12 or this one?

**Comment by michelkluger** [comment]
two different issues, 

the background grey generates some empty rows, that is issue #13
the index has inconsistent formatting when true, that is issue #12

**Comment by sbi-rviot** [comment]
Please do not mix the issues.

As explained, what you think is an issue is actually my library not understanding the `even_bg_color` argument you are giving it. Hence it uses the default one which is **white**. Please do an inspect on your table to see it. As I cannot replicate your issue, I do not think I can help you further than that.

Please come back with more details if you wish to reopen this issue.
