### ISSUE TITLE
Issue with 

### ISSUE THREAD

**Issue by yossisp1972** [sbi-rviot/ph_table#14]
I am using pretty-html-table with pandas to create a table from a nested dictionary.

thats the code

import pandas as pd
import ast
from pretty_html_table import build_table

with open('C:\DevOps_Code\\yaml Parser\\test_new.txt') as file:
  data=file.read()
  d = ast.literal_eval(data)
  dframe = pd.DataFrame(d).T
  dframe.fillna('N/A', inplace=True)
  html_table_blue_light = build_table(dframe, 'blue_light')

with open('c:\devops_code\yaml parser\\test_pandas_1.html' ,'w') as p:
  print(html_table_blue_light, file=p)

The issue is that when using  dframe = pd.DataFrame(d).T to transpose the table ( i need to use this because its a nested dictionary, the first column is omitted.
I've attached the dictionary file i am using.

[test_new.txt](https://github.com/sbi-rviot/ph_table/files/6649767/test_new.txt)
ive also attached how it looks like with to_html using pandas.

![image](https://user-images.githubusercontent.com/46672457/121927301-8c96d780-cd47-11eb-839b-d0a67168bb8f.png)

Any way around this?

**Comment by sbi-rviot** [comment]
Yes - you can use the index option.

Like so:

```
import pandas as pd
import ast
from pretty_html_table import build_table

with open('C:\DevOps_Code\yaml Parser\test_new.txt') as file:
data=file.read()
d = ast.literal_eval(data)
dframe = pd.DataFrame(d).T
dframe.fillna('N/A', inplace=True)
html_table_blue_light = build_table(dframe, 'blue_light')

with open('c:\devops_code\yaml parser\test_pandas_1.html' ,'w') as p:
print(html_table_blue_light, file=p)
```

Could you please confirm?
