### ISSUE TITLE
Option of having same color for all rows is needed.

### ISSUE THREAD

**Issue by rajnathsah** [sbi-rviot/ph_table#15]

**Comment by sbi-rviot** [comment]
Hello @rajnathsah ,
Thanks for using my library :)
Could you please take some time in describing what you would like to see in terms of enhancements? (images, code, issue ...)
Have a great day,
Renaud

**Comment by sbi-rviot** [comment]
I am closing the issue for now - lack of clarity regarding the request.

**Comment by rajnathsah** [comment]
Sorry for late response. Currently table gets generated with alternate row colors, but i was looking to have same colors for all data row. I tried looking at the documents and code but could not find option.
