### ISSUE TITLE
Select data by Tabs

### ISSUE THREAD

**Issue by RyRy1234Ry** [sbi-rviot/ph_table#18]
Are you able to select a certain tab from the workbook to choose that to create the table - or is it just the first tab?

**Comment by sbi-rviot** [comment]
That's not really a **ph_table** question, but on pd.read_excel, you have an optional argument which is "sheet_name" where you can explicitly tell the name of the sheet you wish to use:

https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html
