### ISSUE TITLE
Colour text/floats/integers/... based on their value

### ISSUE THREAD

**Issue by danieldeconinck** [sbi-rviot/ph_table#20]
Hi,

To make big tables a bit more readable and to visualise anomalies, colouring the values based on specific criteria could be quite helpful.  Eg. Positive values green, negative values red, specific colours for specific words ...

Tx,
Daniel

**Comment by sbi-rviot** [comment]
FYI - Working on it!

**Comment by maquinuz** [comment]
That would be great ! I'm trying to combine it with some formating but is not working.... 

![image](https://user-images.githubusercontent.com/313022/140823068-07314a0f-eb8a-46fe-83cf-ac612799418c.png)

When I try to render... it dos not work.... 

![image](https://user-images.githubusercontent.com/313022/140823155-d031f7f8-b39f-4816-8ae3-15e2e4f9f82b.png)

**Comment by sbi-rviot** [comment]
Hello!

I have been working on a condition system that works for numbers. it is deployed in the version 15 of the package.

If you have for instance a column with the name "Age" and you wish to have a red if it is under 25 and green if it is over 60, then you would add the following argument to the `build_table` function:

```
conditions={
                    'Age': {
                        'min': 25,
                        'max': 60,
                        'min_color': 'red',
                        'max_color': 'green',
                    }
                }
```

It would then show the following:

![image](https://user-images.githubusercontent.com/47696569/143864289-222b4004-7eb4-47d6-875f-5cc17de25fb4.png)

**Comment by maquinuz** [comment]
Excellent ! That is such great news !! I will try it out over weekend and let you know, thanks so much for helping out ! 

`>(^_^)<`
