### ISSUE TITLE
Conditional formatting

### ISSUE THREAD

**Issue by selesnow** [sbi-rviot/ph_table#22]
Hi, 

Are you planning to add the ability to conditionally format table fields?

**Comment by sbi-rviot** [comment]
Hello!

I have been working on a condition system that works for numbers. it is deployed in the version 15 of the package.

If you have for instance a column with the name "Age" and you wish to have a red if it is under 25 and green if it is over 60, then you would add the following argument to the `build_table` function:

```
conditions={
                    'Age': {
                        'min': 25,
                        'max': 60,
                        'min_color': 'red',
                        'max_color': 'green',
                    }
                }
```

It would then show the following:

![image](https://user-images.githubusercontent.com/47696569/143864289-222b4004-7eb4-47d6-875f-5cc17de25fb4.png)
