### ISSUE TITLE
Auto-sizing columns doesnt work anymore

### ISSUE THREAD

**Issue by fdmccnll** [sbi-rviot/ph_table#23]
Hey man! 
Great work on PHT, I'm using it since a lot of time.
I noticed lately the size of the columns are not automatically adjusted anymore (even if I force with width="auto").

This suddenly happens one day, no modification to the script whatsover, i think it's due to a new release/update of MS Outlook.

Would be super-nice if you take a look!

Thanks!

**Comment by sbi-rviot** [comment]
Hello,
I can take a look ... it is odd ... I hope we can fix it :)

**Comment by sbi-rviot** [comment]
I could not see this but we added a new argument allowing you to update each of the columns width separately! You would add the following argument to the function `build_table`:

`width_dict=['10px','700px', '50px', '10px','200px', '50px']`

(it needs to be a dict matching the length of your dataframe columns)
and it will give you the following:

![image](https://user-images.githubusercontent.com/47696569/143864600-ae4bad17-2de8-4924-91d3-e4a840f47587.png)
