### ISSUE TITLE
`index=True` seems to break the table formatting

### ISSUE THREAD

**Issue by Nishan-Pradhan** [sbi-rviot/ph_table#25]
When setting  ```index=True``` the formatting of the table seems to be lost

![image](https://user-images.githubusercontent.com/61545498/141974976-f01997b5-6de6-47de-8b7d-b977dd8e67d0.png)

`pretty_html_table 0.9.14`

**Comment by sbi-rviot** [comment]
Hello @Nishan-Pradhan, could you paste here a sample of your code I could use to replicate this issue please?

**Comment by sbi-rviot** [comment]
Need example to be able to solve the issue. Closing for now.
