### ISSUE TITLE
Decimals

### ISSUE THREAD

**Issue by danieltomaselli** [sbi-rviot/ph_table#27]
I think the library doesn't keep the right formatting of float numbers. 

In particular, it loses the last decimal if it is equal to zero. For example, the number 2.22 will appear in the pretty table as 2.22; but the number 2.30 will appear as 2.3 only. 

I have used df.apply(pd.to_numeric, errors='coerce') and df.round(decimals=2) before converting into a table, but it doesn't work. 

Am I doing something wrong or it could be a bug?

thank you

**Comment by sbi-rviot** [comment]
Hello @danieltomaselli ,

It might be a bug, I will take a look :)
In concept, it does not seem like an error, but i understand that it is not ideal for presentation sake.

**Comment by danieltomaselli** [comment]
Thank you for letting me know. Should be ever be improved I will be very happy, otherwise we’ll done for the library I think it brings benefits for many people, including me. Si thank you 🤗

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sbi-rviot** [comment]
Thank you for this kind answer!

**Comment by sbi-rviot** [comment]
Closing thanks to this workaround for now.
