### ISSUE TITLE
HyperLink Issue

### ISSUE THREAD

**Issue by hussain0614** [sbi-rviot/ph_table#28]
Hi,

I am building a table from an excel file where the first column in my excel file has values which are having a URL.
However, when I execute the code the column containing URLs does not contain the hyperlink.

Thanks!

**Comment by sbi-rviot** [comment]
Hello!
Not sure it is an issue :)

I implemented this a while ago:

**index** (bolean) False by default - If you write index=True, index of the dataframe will then be visible in your table.

Could you try?

**Comment by hussain0614** [comment]
Hi,

So by using 'index=True' I get the dataframe index value i.e (0,1,2,3...) however that is not the issue which I am facing.

The issue background is explained below.

1. There is an excel file with data starting from Column A, B, C, D, E, F and G.
2. Column A data has values with a hyperlink
3. When I execute the command 'build_table()' the table gets generated from the excel file however the hyperlinks present in Column A are missing in the generated table.

So the issue here is how to include the missing hyperlinks in the generated table which are missing since the excel file does have the hyperlink.

Thanks

**Comment by hussain0614** [comment]
Hi,

Any workaround available for this?

Thanks

**Comment by simoncook** [comment]
You can code the hyperlink with the appropriate html tags - 
for example the first column entry might be <a href="http://www.disney.com">Disney</a> - but then you need to make sure in the build table, you set the escape parameter to False - this stops the tags being made HTML safe

**Comment by sbi-rviot** [comment]
Closing for now
