### ISSUE TITLE
Is there an easy way to left align columns with text and right align columns with numbers?

### ISSUE THREAD

**Issue by ededovic** [sbi-rviot/ph_table#29]
I'd like to be able to generate a table like this, ignoring the shading:

![image](https://user-images.githubusercontent.com/9282127/157916017-793c2b7a-236d-455f-a062-6d3fe9aa89c7.png)

I tried padding numbers from the left, so they line up on the right and then text-align left, but browser still somehow ignores empty spaces. 

```
for c in df.select_dtypes(['int','float64']).columns:
    df[c] = df[c].astype(str).str.rjust(int(df[c].astype(str).str.len().max()),' ')
```

**Comment by sbi-rviot** [comment]
Today, we only apply it on the entire table.
We could add conditions on it, but it is not implemented yet:

text_align - accepts standard html property values such as left, right, center, justify.
