### ISSUE TITLE
Add font size argument to build_table()

### ISSUE THREAD

**Issue by selesnow** [sbi-rviot/ph_table#3]
Hello, thank for pretty_html_table!

Can you add some arguments to build_table() for make it more flexible?

For example:
* `font_size`
* `font_style`
* `font_family` 
* etc...

**Comment by sbi-rviot** [comment]
Hello,

You are welcome!
it is a good idea. 
I will look into this this week.

**Comment by selesnow** [comment]
Very thx!

I [wrote](https://alexeyseleznev.wordpress.com/2020/04/30/python-%d0%ba%d0%b0%d0%ba-%d1%81%d0%be%d0%b7%d0%b4%d0%b0%d1%82%d1%8c-%d0%be%d1%84%d0%be%d1%80%d0%bc%d0%bb%d0%b5%d0%bd%d0%bd%d1%83%d1%8e-html-%d1%82%d0%b0%d0%b1%d0%bb%d0%b8%d1%86%d1%83-%d0%b8%d0%b7-pa/) article for russian language users of pretty_html_table.

**Comment by sbi-rviot** [comment]
With this new version, you can now change the alignment and the style:

pretty-html-table 0.8.dev0

build_table(df, color, font_family = 'Century Gothic', text_align = 'left')

**Comment by selesnow** [comment]
Thanks!

Can you add text_size argument?

**Comment by selesnow** [comment]
I send pull request for you with font_size argument.

Example of use:

```python
import pretty_html_table
import pandas as pd

d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)

dfhtml = pretty_html_table.build_table(df, 'blue_light', font_size = '10px')
```

**Comment by sbi-rviot** [comment]
thank you.
I implemented the change in v9 of the library.
