### ISSUE TITLE
width_dict casues html lose some formatting

### ISSUE THREAD

**Issue by sootytm1** [sbi-rviot/ph_table#31]
When using width_dict to specify columns widths, the resulting html output losing some formatting with multiple "/n" appearing at the top of the table. Using the width property for all columns performs as expected.

**Comment by Sm4o** [comment]
@sbi-rviot I found a potential solution and created the PR above

**Comment by sbi-rviot** [comment]
Hello!
Thank you for your contribution.
I am on vacations now, but I’ll look at it end of April/ beginning of May.
