### ISSUE TITLE
Conditions Not working if column contains '0' 

### ISSUE THREAD

**Issue by morris-itathn** [sbi-rviot/ph_table#35]
`   conditions={'Test': {'min': 29,'max': 39,'min_color': 'red','max_color': 'blue'}})
`

![image](https://user-images.githubusercontent.com/70922298/172922214-cdbb7817-673c-49bb-9dd4-6471e21cec06.png)

![image](https://user-images.githubusercontent.com/70922298/172922128-28407d34-d8bf-43d1-8669-d3443c88c6c6.png)

**Comment by sbi-rviot** [comment]
I will take a look :)

**Comment by morris-itathn** [comment]
💘 thank you kind sir

**Comment by morris-itathn** [comment]
This was caused by pandas' .fillna(0). 
Converting column value's to integers corrected this, i.e 
`Data = Data.astype({'col1': int, 'col2': int, 'col3': int, 'col4': int})`
